"""
Approval Request Service - Human-in-the-loop approval workflow

Creates Proposed_Action.md documents and polls for approval decisions
before executing high-risk or external actions.
"""

import logging
import re
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

logger = logging.getLogger(__name__)


@dataclass
class ApprovalAction:
    """Represents an action awaiting approval"""
    title: str
    plan_reference: str
    risk_level: Literal["Low", "Medium", "High"]
    summary: str
    approved: Literal["PENDING", "Yes", "No"] = "PENDING"
    created_timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    reviewed_timestamp: datetime | None = None
    reviewer_notes: str | None = None
    executed_timestamp: datetime | None = None
    result: str | None = None
    
    def to_markdown(self, action_id: str = "") -> str:
        """Convert to markdown format for storage"""
        return f"""---
Title: {self.title}
Plan_Reference: {self.plan_reference}
Risk_Level: {self.risk_level}
Summary: {self.summary}
Approved: {self.approved}
Created: {self.created_timestamp.isoformat().replace('+00:00', 'Z')}
Reviewed: {self.reviewed_timestamp.isoformat() if self.reviewed_timestamp else 'null'}
Reviewer_Notes: {self.reviewer_notes or 'null'}
Executed: {self.executed_timestamp.isoformat() if self.executed_timestamp else 'null'}
Result: {self.result or 'null'}
Action_ID: {action_id}
---

# Action: {self.title}

**Plan Reference**: {self.plan_reference}

**Risk Level**: {self.risk_level}

**Summary**: {self.summary}

**Status**: {self.approved}

## Approval Instructions

1. Review the action details above
2. Check the Plan reference for full execution steps
3. Edit this file: set `Approved: Yes` or `Approved: No`
4. Save file - system will detect change and act accordingly

## Decision

Edit the `Approved` field in the frontmatter above.

**Current Status**: {self.approved}

## Reviewer Notes

{self.reviewer_notes or "*Add your comments here*"}

---
*Generated by Approval Request Service*
"""
    
    @classmethod
    def from_markdown(cls, content: str) -> "ApprovalAction":
        """Parse from markdown format"""
        # Extract frontmatter
        match = re.search(r"---\n(.*?)\n---", content, re.DOTALL)
        if not match:
            raise ValueError("Invalid action markdown format")
        
        frontmatter = match.group(1)
        fields = {}
        
        for line in frontmatter.split("\n"):
            if ":" in line:
                key, value = line.split(":", 1)
                key = key.strip()
                value = value.strip()
                
                if value == "null":
                    value = None
                elif key == "Approved":
                    if value not in ["PENDING", "Yes", "No"]:
                        value = "PENDING"
                elif key == "Created" and value:
                    value = datetime.fromisoformat(value.replace("Z", "+00:00"))
                elif key == "Reviewed" and value:
                    value = datetime.fromisoformat(value.replace("Z", "+00:00"))
                elif key == "Executed" and value:
                    value = datetime.fromisoformat(value.replace("Z", "+00:00"))
                
                fields[key] = value
        
        return cls(
            title=fields.get("Title", "Untitled Action"),
            plan_reference=fields.get("Plan_Reference", ""),
            risk_level=fields.get("Risk_Level", "Medium"),
            summary=fields.get("Summary", ""),
            approved=fields.get("Approved", "PENDING"),
            created_timestamp=fields.get("Created", datetime.now(timezone.utc)),
            reviewed_timestamp=fields.get("Reviewed"),
            reviewer_notes=fields.get("Reviewer_Notes"),
            executed_timestamp=fields.get("Executed"),
            result=fields.get("Result")
        )


class ApprovalRequest:
    """
    Manage approval requests for high-risk actions.
    
    Creates Proposed_Action.md documents and provides
    polling mechanism to detect approval decisions.
    """
    
    def __init__(
        self,
        actions_dir: Path | None = None,
        dashboard_path: Path | None = None,
        done_dir: Path | None = None,
    ):
        """
        Initialize approval request service.
        
        Args:
            actions_dir: Directory for action storage (default: Proposed_Actions)
            dashboard_path: Path to Dashboard.md for logging
            done_dir: Directory for completed/rejected actions (default: Done/Rejected)
        """
        project_root = Path(__file__).parent.parent.parent
        self.actions_dir = actions_dir or (project_root / "AI_Employee_Vault" / "Proposed_Actions")
        self.dashboard_path = dashboard_path or (project_root / "AI_Employee_Vault" / "Dashboard.md")
        self.done_dir = done_dir or (project_root / "AI_Employee_Vault" / "Done" / "Rejected")
        
        self.actions_dir.mkdir(parents=True, exist_ok=True)
        self.done_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info("ApprovalRequest initialized")
    
    def _get_next_action_number(self) -> int:
        """Get next sequential action number for today"""
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        
        if not self.actions_dir.exists():
            return 1
        
        existing = list(self.actions_dir.glob(f"Action_{today}_*.md"))
        return len(existing) + 1
    
    def _generate_action_id(self) -> str:
        """Generate unique action ID"""
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        number = self._get_next_action_number()
        return f"Action_{today}_{number:03d}"
    
    def _log_to_dashboard(
        self,
        action_id: str,
        decision: str,
        decision_time_min: float,
        reviewer_notes: str = "",
    ):
        """Log approval decision to Dashboard.md"""
        timestamp = datetime.now(timezone.utc).isoformat()
        notes = reviewer_notes[:50] + "..." if len(reviewer_notes or "") > 50 else (reviewer_notes or "")
        log_entry = f"| {timestamp} | {action_id} | {decision} | {decision_time_min:.1f} min | {notes} |\n"
        
        try:
            if self.dashboard_path.exists():
                content = self.dashboard_path.read_text(encoding="utf-8")
                
                # Find Approval Decisions table
                if "### Approval Decisions" in content:
                    lines = content.split("\n")
                    new_lines = []
                    inserted = False
                    
                    for line in lines:
                        new_lines.append(line)
                        if line.startswith("| Timestamp |") and "Action ID" in line and not inserted:
                            new_lines.append(log_entry.rstrip())
                            inserted = True
                    
                    content = "\n".join(new_lines)
                else:
                    content += f"\n### Approval Decisions\n\n| Timestamp | Action ID | Decision | Decision Time | Reviewer Notes |\n|-----------|-----------|----------|---------------|----------------|\n{log_entry}"
                
                self.dashboard_path.write_text(content, encoding="utf-8")
        except Exception as e:
            logger.error(f"Failed to log to dashboard: {e}")
    
    def create_approval_request(
        self,
        title: str,
        plan_reference: str,
        summary: str,
        risk_level: Literal["Low", "Medium", "High"] = "Medium",
    ) -> tuple[ApprovalAction, str]:
        """
        Create a new approval request.
        
        Args:
            title: Action title
            plan_reference: Path to Plan.md being requested
            summary: Human-readable action summary
            risk_level: Risk level
        
        Returns:
            Tuple of (ApprovalAction object, action_id)
        """
        action = ApprovalAction(
            title=title,
            plan_reference=plan_reference,
            risk_level=risk_level,
            summary=summary
        )
        
        action_id = self._generate_action_id()
        
        # Save to file
        action_file = self.actions_dir / f"{action_id}.md"
        action_file.write_text(action.to_markdown(action_id), encoding="utf-8")
        
        logger.info(f"Created approval request: {action_id} for plan: {plan_reference}")
        
        return action, action_id
    
    def check_approval_status(self, action_id: str) -> Literal["PENDING", "APPROVED", "REJECTED"]:
        """
        Check approval status of an action.
        
        Args:
            action_id: Action ID to check
        
        Returns:
            Current status
        """
        action_file = self.actions_dir / f"{action_id}.md"
        
        if not action_file.exists():
            raise FileNotFoundError(f"Action {action_id} not found")
        
        content = action_file.read_text(encoding="utf-8")
        action = ApprovalAction.from_markdown(content)
        
        if action.approved == "Yes":
            return "APPROVED"
        elif action.approved == "No":
            return "REJECTED"
        else:
            return "PENDING"
    
    def poll_pending_actions(self, callback_approved=None, callback_rejected=None):
        """
        Poll all pending actions for approval decisions.
        
        Args:
            callback_approved: Function to call for approved actions (receives action_id)
            callback_rejected: Function to call for rejected actions (receives action_id)
        """
        if not self.actions_dir.exists():
            return
        
        for action_file in self.actions_dir.glob("Action_*.md"):
            try:
                content = action_file.read_text(encoding="utf-8")
                action = ApprovalAction.from_markdown(content)
                
                if action.approved == "Yes":
                    logger.info(f"Action {action_file.stem} approved")
                    
                    # Update timestamps
                    action.reviewed_timestamp = datetime.now(timezone.utc)
                    decision_time = (action.reviewed_timestamp - action.created_timestamp).total_seconds() / 60
                    
                    self._log_to_dashboard(
                        action_file.stem,
                        "Approved",
                        decision_time,
                        action.reviewer_notes or ""
                    )
                    
                    if callback_approved:
                        callback_approved(action_file.stem)
                
                elif action.approved == "No":
                    logger.info(f"Action {action_file.stem} rejected")
                    
                    # Update timestamps
                    action.reviewed_timestamp = datetime.now(timezone.utc)
                    decision_time = (action.reviewed_timestamp - action.created_timestamp).total_seconds() / 60
                    
                    action.result = "Rejected by reviewer"
                    action.executed_timestamp = datetime.now(timezone.utc)
                    
                    self._log_to_dashboard(
                        action_file.stem,
                        "Rejected",
                        decision_time,
                        action.reviewer_notes or ""
                    )
                    
                    # Move to Done/Rejected
                    rejected_file = self.done_dir / action_file.name
                    action_file.rename(rejected_file)
                    
                    if callback_rejected:
                        callback_rejected(action_file.stem)
            
            except Exception as e:
                logger.error(f"Failed to check action {action_file.name}: {e}")
    
    def wait_for_approval(
        self,
        action_id: str,
        timeout_minutes: int = 60,
        poll_interval_seconds: int = 60,
    ) -> Literal["APPROVED", "REJECTED", "TIMEOUT"]:
        """
        Wait for approval decision on an action.
        
        Args:
            action_id: Action ID to wait for
            timeout_minutes: Maximum wait time
            poll_interval_seconds: Polling interval
        
        Returns:
            Final status
        """
        start_time = time.time()
        timeout_seconds = timeout_minutes * 60
        
        logger.info(f"Waiting for approval on {action_id} (timeout: {timeout_minutes}min)")
        
        while time.time() - start_time < timeout_seconds:
            status = self.check_approval_status(action_id)
            
            if status in ["APPROVED", "REJECTED"]:
                return status
            
            time.sleep(poll_interval_seconds)
        
        logger.warning(f"Approval timeout for {action_id}")
        return "TIMEOUT"


if __name__ == "__main__":
    # Test approval request
    service = ApprovalRequest()
    
    action, action_id = service.create_approval_request(
        title="Test Action",
        plan_reference="Plans/Plan_20260221_001.md",
        summary="Test approval workflow",
        risk_level="Medium"
    )
    
    print(f"Created approval request: {action_id}")
    print(f"Status: {action.approved}")
    print(f"File: Proposed_Actions/{action_id}.md")
