"""
Plan Generator Service - Generate structured execution plans

Creates Plan.md documents for multi-step tasks, external actions,
and high-risk workflows.
"""

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

logger = logging.getLogger(__name__)


@dataclass
class PlanStep:
    """A single step in a plan"""
    step_number: int
    skill_name: str
    description: str
    dependencies: list[int] = field(default_factory=list)


@dataclass
class Plan:
    """Structured execution plan"""
    title: str
    objective: str
    risk_level: Literal["Low", "Medium", "High"]
    approval_required: bool
    steps: list[PlanStep]
    expected_outcome: str
    rollback_strategy: str
    created_timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    status: Literal["Draft", "Active", "Completed", "Rolled_Back"] = "Draft"
    executed_timestamp: datetime | None = None
    result_summary: str | None = None
    
    def to_markdown(self, plan_id: str = "") -> str:
        """Convert to markdown format for storage"""
        steps_md = ""
        for step in self.steps:
            deps = f" (depends on: {step.dependencies})" if step.dependencies else ""
            steps_md += f"\n{step.step_number}. **{step.skill_name}**{deps}\n"
            steps_md += f"   - {step.description}\n"
        
        return f"""---
Title: {self.title}
Objective: {self.objective}
Risk_Level: {self.risk_level}
Approval_Required: {self.approval_required}
Created: {self.created_timestamp.isoformat().replace('+00:00', 'Z')}
Status: {self.status}
Plan_ID: {plan_id}
---

# Plan: {self.title}

**Objective**: {self.objective}

**Risk Level**: {self.risk_level}

**Approval Required**: {"Yes" if self.approval_required else "No"}

## Steps

{steps_md}

## Expected Outcome

{self.expected_outcome}

## Rollback Strategy

{self.rollback_strategy}

---
*Generated by Plan Generator Service*
"""
    
    @classmethod
    def from_markdown(cls, content: str) -> "Plan":
        """Parse from markdown format"""
        # Extract frontmatter
        match = re.search(r"---\n(.*?)\n---", content, re.DOTALL)
        if not match:
            raise ValueError("Invalid plan markdown format")
        
        frontmatter = match.group(1)
        fields = {}
        
        for line in frontmatter.split("\n"):
            if ":" in line:
                key, value = line.split(":", 1)
                key = key.strip()
                value = value.strip().strip('"')
                
                if value == "true":
                    value = True
                elif value == "false":
                    value = False
                elif key in ["Approval_Required"]:
                    value = value == "Yes" or value == "true"
                elif key == "Created":
                    value = datetime.fromisoformat(value.replace("Z", "+00:00"))
                elif key == "Status":
                    if value not in ["Draft", "Active", "Completed", "Rolled_Back"]:
                        value = "Draft"
                elif key == "Risk_Level":
                    if value not in ["Low", "Medium", "High"]:
                        value = "Medium"
                
                fields[key] = value
        
        # Parse steps (simplified)
        steps = []
        
        return cls(
            title=fields.get("Title", "Untitled Plan"),
            objective=fields.get("Objective", ""),
            risk_level=fields.get("Risk_Level", "Medium"),
            approval_required=fields.get("Approval_Required", False),
            steps=steps,
            expected_outcome=fields.get("Expected_Outcome", ""),
            rollback_strategy=fields.get("Rollback_Strategy", "Manual intervention required"),
            created_timestamp=fields.get("Created", datetime.now(timezone.utc)),
            status=fields.get("Status", "Draft")
        )


class PlanGenerator:
    """
    Generate structured execution plans for complex tasks.
    
    Triggers:
    - Multi-step execution (3+ skill invocations)
    - External action required (MCP server call)
    - High-risk task detected
    - Business posting (LinkedIn, external communication)
    """
    
    def __init__(
        self,
        plans_dir: Path | None = None,
        dashboard_path: Path | None = None,
    ):
        """
        Initialize plan generator.
        
        Args:
            plans_dir: Directory for plan storage (default: Plans)
            dashboard_path: Path to Dashboard.md for logging
        """
        project_root = Path(__file__).parent.parent.parent
        self.plans_dir = plans_dir or (project_root / "AI_Employee_Vault" / "Plans")
        self.dashboard_path = dashboard_path or (project_root / "AI_Employee_Vault" / "Dashboard.md")
        
        self.plans_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info("PlanGenerator initialized")
    
    def _get_next_plan_number(self) -> int:
        """Get next sequential plan number for today"""
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        
        if not self.plans_dir.exists():
            return 1
        
        # Find existing plans for today
        existing = list(self.plans_dir.glob(f"Plan_{today}_*.md"))
        return len(existing) + 1
    
    def _generate_plan_id(self) -> str:
        """Generate unique plan ID"""
        today = datetime.now(timezone.utc).strftime("%Y%m%d")
        number = self._get_next_plan_number()
        return f"Plan_{today}_{number:03d}"
    
    def _log_to_dashboard(
        self,
        plan_id: str,
        risk_level: str,
        approval_required: bool,
        objective: str,
    ):
        """Log plan creation to Dashboard.md"""
        timestamp = datetime.now(timezone.utc).isoformat()
        log_entry = f"| {timestamp} | {plan_id} | {risk_level} | {'Yes' if approval_required else 'No'} | {objective} |\n"
        
        try:
            if self.dashboard_path.exists():
                content = self.dashboard_path.read_text(encoding="utf-8")
                
                # Find Plan Creations table
                if "### Plan Creations" in content:
                    lines = content.split("\n")
                    new_lines = []
                    inserted = False
                    
                    for line in lines:
                        new_lines.append(line)
                        if line.startswith("| Timestamp |") and "Plan ID" in line and not inserted:
                            new_lines.append(log_entry.rstrip())
                            inserted = True
                    
                    content = "\n".join(new_lines)
                else:
                    # Append to end
                    content += f"\n### Plan Creations\n\n| Timestamp | Plan ID | Risk Level | Approval Required | Objective |\n|-----------|---------|------------|-------------------|-----------|\n{log_entry}"
                
                self.dashboard_path.write_text(content, encoding="utf-8")
        except Exception as e:
            logger.error(f"Failed to log to dashboard: {e}")
    
    def assess_risk(self, task_description: str, requires_external: bool = False, requires_mcp: bool = False) -> Literal["Low", "Medium", "High"]:
        """
        Assess risk level of a task.
        
        Args:
            task_description: Task description
            requires_external: Whether task requires external API
            requires_mcp: Whether task requires MCP server
        
        Returns:
            Risk level: Low, Medium, or High
        """
        risk_indicators = [
            "delete", "remove", "destroy", "permanent",
            "send", "post", "publish", "external",
            "payment", "money", "financial",
            "credential", "password", "secret",
        ]
        
        risk_score = 0
        
        # Check for risk indicators
        task_lower = task_description.lower()
        for indicator in risk_indicators:
            if indicator in task_lower:
                risk_score += 1
        
        # External actions increase risk
        if requires_external:
            risk_score += 1
        if requires_mcp:
            risk_score += 1
        
        # Determine risk level
        if risk_score >= 3:
            return "High"
        elif risk_score >= 1:
            return "Medium"
        else:
            return "Low"
    
    def should_require_approval(self, risk_level: str, requires_mcp: bool) -> bool:
        """
        Determine if task requires human approval.
        
        Args:
            risk_level: Task risk level
            requires_mcp: Whether task requires MCP server
        
        Returns:
            True if approval required
        """
        # High risk always requires approval
        if risk_level == "High":
            return True
        
        # MCP actions (external writes) require approval
        if requires_mcp:
            return True
        
        return False
    
    def create_plan(
        self,
        title: str,
        objective: str,
        steps: list[dict],
        risk_level: Literal["Low", "Medium", "High"] | None = None,
        approval_required: bool | None = None,
        expected_outcome: str = "",
        rollback_strategy: str = "Manual intervention required",
        requires_mcp: bool = False,
    ) -> tuple[Plan, str]:
        """
        Create a new execution plan.
        
        Args:
            title: Plan title
            objective: Plan objective
            steps: List of step dicts with keys: skill_name, description, dependencies
            risk_level: Optional risk level (auto-assessed if not provided)
            approval_required: Optional approval flag (auto-calculated if not provided)
            expected_outcome: Expected result
            rollback_strategy: How to undo if failed
            requires_mcp: Whether plan requires MCP actions
        
        Returns:
            Tuple of (Plan object, plan_id)
        """
        # Auto-assess risk if not provided
        if risk_level is None:
            risk_level = self.assess_risk(objective, requires_mcp=requires_mcp)
        
        # Auto-calculate approval if not provided
        if approval_required is None:
            approval_required = self.should_require_approval(risk_level, requires_mcp)
        
        # Create steps
        plan_steps = []
        for i, step_data in enumerate(steps, 1):
            plan_steps.append(PlanStep(
                step_number=i,
                skill_name=step_data.get("skill_name", "Unknown"),
                description=step_data.get("description", ""),
                dependencies=step_data.get("dependencies", [])
            ))
        
        # Create plan
        plan = Plan(
            title=title,
            objective=objective,
            risk_level=risk_level,
            approval_required=approval_required,
            steps=plan_steps,
            expected_outcome=expected_outcome,
            rollback_strategy=rollback_strategy
        )
        
        # Generate plan ID
        plan_id = self._generate_plan_id()
        
        # Save to file
        plan_file = self.plans_dir / f"{plan_id}.md"
        plan_file.write_text(plan.to_markdown(plan_id), encoding="utf-8")
        
        # Log to dashboard
        self._log_to_dashboard(plan_id, risk_level, approval_required, objective)
        
        logger.info(f"Created plan: {plan_id} (risk: {risk_level}, approval: {approval_required})")
        
        return plan, plan_id


if __name__ == "__main__":
    # Test plan generation
    generator = PlanGenerator()
    
    plan, plan_id = generator.create_plan(
        title="Test Plan",
        objective="Test plan generation",
        steps=[
            {"skill_name": "Test Skill 1", "description": "First step", "dependencies": []},
            {"skill_name": "Test Skill 2", "description": "Second step", "dependencies": [1]},
        ],
        requires_mcp=True
    )
    
    print(f"Created plan: {plan_id}")
    print(f"Risk level: {plan.risk_level}")
    print(f"Approval required: {plan.approval_required}")
