"""Daily Summary - Generates daily business summaries."""

import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List


class DailySummary:
    """Generates daily business summaries and briefings.
    
    This scheduler task:
    1. Runs daily at 8:00 AM
    2. Summarizes yesterday's activity
    3. Creates CEO briefing document
    4. Updates Dashboard with summary
    """
    
    def __init__(self, vault_path: str):
        """Initialize the daily summary generator.
        
        Args:
            vault_path: Path to the Obsidian vault root
        """
        self.vault_path = Path(vault_path)
        self.briefings = self.vault_path / 'Briefings'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure directories exist
        self.briefings.mkdir(parents=True, exist_ok=True)
        
        self.logger = logging.getLogger(self.__class__.__name__)
    
    def generate_summary(self) -> Path:
        """Generate a daily summary briefing.
        
        Returns:
            Path to the generated briefing file
        """
        today = datetime.now()
        yesterday = today - timedelta(days=1)
        
        # Create briefing file
        briefing_file = self.briefings / f'Daily_{yesterday.strftime("%Y-%m-%d")}.md'
        
        # Gather metrics
        metrics = self._gather_metrics(yesterday)
        
        content = f"""---
type: daily_briefing
date: {yesterday.strftime('%Y-%m-%d')}
generated: {today.isoformat()}
---

# Daily Briefing - {yesterday.strftime('%A, %B %d, %Y')}

## Executive Summary

Generated at {today.strftime('%H:%M')}. This briefing summarizes activity for {yesterday.strftime('%B %d, %Y')}.

---

## 📊 Key Metrics

| Metric | Count |
|--------|-------|
| Emails Processed | {metrics.get('emails', 0)} |
| Files Processed | {metrics.get('files', 0)} |
| Tasks Completed | {metrics.get('tasks_completed', 0)} |
| Plans Created | {metrics.get('plans', 0)} |
| Approvals Pending | {metrics.get('approvals_pending', 0)} |
| LinkedIn Posts | {metrics.get('linkedin_posts', 0)} |

---

## 📧 Email Activity

{self._summarize_emails(yesterday)}

---

## 📁 File Processing

{self._summarize_files(yesterday)}

---

## ✅ Completed Tasks

{self._summarize_completed_tasks(yesterday)}

---

## ⏰ Pending Items

{self._summarize_pending()}

---

## 📝 Notes



---

*Generated by DailySummary*
*Silver Tier - AI Employee*
"""
        
        briefing_file.write_text(content)
        self.logger.info(f"Generated daily briefing: {briefing_file.name}")
        
        # Update dashboard
        self._update_dashboard(briefing_file)
        
        return briefing_file
    
    def _gather_metrics(self, date: datetime) -> Dict:
        """Gather metrics for the specified date."""
        metrics = {
            'emails': 0,
            'files': 0,
            'tasks_completed': 0,
            'plans': 0,
            'approvals_pending': 0,
            'linkedin_posts': 0
        }
        
        date_str = date.strftime('%Y-%m-%d')
        
        # Count emails
        email_logs = self.logs / f'email_{date_str}.md'
        if email_logs.exists():
            content = email_logs.read_text()
            metrics['emails'] = content.count('## Email')
        
        # Count files processed
        done_folder = self.done
        if done_folder.exists():
            for f in done_folder.glob(f'*{date_str}*'):
                metrics['files'] += 1
        
        # Count plans created
        plans_folder = self.vault_path / 'Plans'
        if plans_folder.exists():
            for f in plans_folder.glob(f'Plan_*{date_str.replace("-", "")}*'):
                metrics['plans'] += 1
        
        # Count pending approvals
        pending_folder = self.vault_path / 'Pending_Approval'
        if pending_folder.exists():
            metrics['approvals_pending'] = len(list(pending_folder.glob('*.md')))
        
        # Count LinkedIn posts
        linkedin_logs = self.logs / f'linkedin_{date_str}.md'
        if linkedin_logs.exists():
            content = linkedin_logs.read_text()
            metrics['linkedin_posts'] = content.count('## Post')
        
        return metrics
    
    def _summarize_emails(self, date: datetime) -> str:
        """Summarize email activity."""
        date_str = date.strftime('%Y-%m-%d')
        email_logs = self.logs / f'email_{date_str}.md'
        
        if email_logs.exists():
            return f"Email logs available: [{email_logs.name}]({email_logs})"
        
        return "No email activity recorded."
    
    def _summarize_files(self, date: datetime) -> str:
        """Summarize file processing activity."""
        return f"Check /Done/ folder for processed files from {date.strftime('%B %d, %Y')}."
    
    def _summarize_completed_tasks(self, date: datetime) -> str:
        """Summarize completed tasks."""
        done_folder = self.done
        if not done_folder.exists():
            return "No completed tasks."
        
        completed = []
        for f in done_folder.glob('*.md'):
            if date.strftime('%Y-%m-%d') in f.read_text():
                completed.append(f.name)
        
        if completed:
            return "\n".join([f"- {item}" for item in completed[:10]])
        
        return "No tasks completed."
    
    def _summarize_pending(self) -> str:
        """Summarize pending items."""
        pending = []
        
        # Check Needs_Action
        needs_action = self.vault_path / 'Needs_Action'
        if needs_action.exists():
            count = len(list(needs_action.glob('*.md')))
            if count > 0:
                pending.append(f"- **Needs Action**: {count} items")
        
        # Check Pending_Approval
        pending_approval = self.vault_path / 'Pending_Approval'
        if pending_approval.exists():
            count = len(list(pending_approval.glob('*.md')))
            if count > 0:
                pending.append(f"- **Pending Approval**: {count} items")
        
        if pending:
            return "\n".join(pending)
        
        return "No pending items."
    
    def _update_dashboard(self, briefing_file: Path):
        """Update Dashboard.md with the new briefing."""
        if not self.dashboard.exists():
            return
        
        content = self.dashboard.read_text()
        
        # Add briefing link to Recent Completions
        briefing_link = f"- [{briefing_file.name}]({briefing_file})"
        
        if '## ✅ Recent Completions' in content:
            content = content.replace(
                '## ✅ Recent Completions\n\n*No recent completions*',
                f"## ✅ Recent Completions\n\n{briefing_link}"
            )
        
        self.dashboard.write_text(content)
        self.logger.info("Dashboard updated with briefing link")
