"""
LinkedIn Mock Test - Test LinkedIn workflow without API access

This module provides a mock LinkedIn posting capability for testing
the approval workflow and MCP integration without requiring LinkedIn API access.

Usage:
    # Run mock test
    python -m ai_employee.mcp_server.actions.linkedin_mock_test
    
    # Execute mock post (simulates LinkedIn posting)
    python -m ai_employee.mcp_server.actions.linkedin_mock_test --execute
"""

import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)


class LinkedInMockPoster:
    """
    Mock LinkedIn poster for testing without API access.
    
    Simulates the LinkedIn posting workflow:
    1. Generate post draft
    2. Create approval request
    3. Wait for approval
    4. "Publish" to vault (mock)
    5. Log to Dashboard
    """

    def __init__(self):
        project_root = Path(__file__).parent.parent.parent
        self.vault_dir = project_root / "AI_Employee_Vault"
        self.plans_dir = self.vault_dir / "Plans"
        self.actions_dir = self.vault_dir / "Proposed_Actions"
        self.done_dir = self.vault_dir / "Done"
        self.dashboard_path = self.vault_dir / "Dashboard.md"
        
        # Ensure directories exist
        self.plans_dir.mkdir(parents=True, exist_ok=True)
        self.actions_dir.mkdir(parents=True, exist_ok=True)
        self.done_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info("LinkedInMockPoster initialized")

    def generate_post_draft(self, content: str, topic: str = "General") -> str:
        """
        Generate a LinkedIn post draft.
        
        Args:
            content: Post content
            topic: Post topic/category
            
        Returns:
            Path to draft file
        """
        timestamp = datetime.now(timezone.utc)
        draft_id = f"LinkedIn_Draft_{timestamp.strftime('%Y%m%d_%H%M%S')}"
        
        draft_content = f"""---
Title: LinkedIn Post Draft
Topic: {topic}
Created: {timestamp.isoformat().replace('+00:00', 'Z')}
Status: Draft
---

# LinkedIn Post Draft

**Topic**: {topic}

**Created**: {timestamp.isoformat()}

## Post Content

{content}

## Hashtags (suggested)

#AI #Automation #Productivity #Tech

## Engagement Goals

- Target impressions: 1000+
- Target engagement rate: 3%+

---
*Generated by LinkedIn Mock Poster*
"""
        
        draft_file = self.plans_dir / f"{draft_id}.md"
        draft_file.write_text(draft_content, encoding="utf-8")
        
        logger.info(f"Generated LinkedIn draft: {draft_file}")
        return str(draft_file)

    def create_approval_request(self, draft_path: str) -> str:
        """
        Create approval request for LinkedIn post.
        
        Args:
            draft_path: Path to draft file
            
        Returns:
            Action ID
        """
        timestamp = datetime.now(timezone.utc)
        action_num = len(list(self.actions_dir.glob("Action_*.md"))) + 1
        action_id = f"Action_{timestamp.strftime('%Y%m%d')}_{action_num:03d}"
        
        action_content = f"""---
Title: LinkedIn Post Publication
Plan_Reference: {draft_path}
Risk_Level: Medium
Summary: Publish LinkedIn post draft to social media
Approved: PENDING
Created: {timestamp.isoformat().replace('+00:00', 'Z')}
---

# Action: LinkedIn Post Publication

**Plan Reference**: {draft_path}

**Risk Level**: Medium

**Summary**: Publish LinkedIn post to LinkedIn platform

**Status**: PENDING

## Approval Instructions

1. Review the LinkedIn post draft
2. Check for appropriate content and tone
3. Verify hashtags are relevant
4. Edit this file: set `Approved: Yes` or `Approved: No`
5. Save file - system will detect change

## Decision

Edit the `Approved` field in the frontmatter above.

**Current Status**: PENDING

---
*Created by LinkedIn Mock Poster*
"""
        
        action_file = self.actions_dir / f"{action_id}.md"
        action_file.write_text(action_content, encoding="utf-8")
        
        logger.info(f"Created approval request: {action_file}")
        return action_id

    def check_approval_status(self, action_id: str) -> str:
        """
        Check if action is approved.
        
        Args:
            action_id: Action ID to check
            
        Returns:
            "APPROVED", "REJECTED", or "PENDING"
        """
        action_file = self.actions_dir / f"{action_id}.md"
        
        if not action_file.exists():
            return "NOT_FOUND"
        
        content = action_file.read_text(encoding="utf-8")
        
        if "Approved: Yes" in content:
            return "APPROVED"
        elif "Approved: No" in content:
            return "REJECTED"
        else:
            return "PENDING"

    def execute_mock_post(self, draft_path: str, action_id: str) -> dict:
        """
        Execute mock LinkedIn post (simulates publishing).
        
        Args:
            draft_path: Path to draft file
            action_id: Approval action ID
            
        Returns:
            Result dict with mock post URL
        """
        timestamp = datetime.now(timezone.utc)
        
        # Read draft content
        draft_content = draft_path.read_text(encoding="utf-8")
        
        # Extract post content
        content_match = re.search(r'## Post Content\n\n(.+?)\n\n## Hashtags', draft_content, re.DOTALL)
        post_content = content_match.group(1).strip() if content_match else "No content"
        
        # Create mock post URL
        mock_post_id = f"mock_{timestamp.strftime('%Y%m%d%H%M%S')}"
        mock_url = f"https://www.linkedin.com/feed/update/{mock_post_id}"
        
        # Create "published" post file
        post_id = f"LinkedIn_Post_{timestamp.strftime('%Y%m%d_%H%M%S')}"
        post_content_md = f"""---
Title: LinkedIn Post Published
Original_Draft: {draft_path}
Approval_Action: {action_id}
Published: {timestamp.isoformat().replace('+00:00', 'Z')}
Status: Published
Mock_URL: {mock_url}
---

# LinkedIn Post - Published

**Original Draft**: {draft_path}

**Approval Action**: {action_id}

**Published**: {timestamp.isoformat()}

**Mock URL**: {mock_url}

## Post Content

{post_content}

## Mock Engagement (simulated)

| Metric | Value |
|--------|-------|
| Impressions | 0 (mock) |
| Likes | 0 (mock) |
| Comments | 0 (mock) |
| Shares | 0 (mock) |

---
*Published by LinkedIn Mock Poster (simulation)*
"""
        
        post_file = self.done_dir / f"{post_id}.md"
        post_file.write_text(post_content_md, encoding="utf-8")
        
        # Update action file with execution result
        action_file = self.actions_dir / f"{action_id}.md"
        action_content = action_file.read_text(encoding="utf-8")
        action_content = action_content.replace(
            "**Current Status**: PENDING",
            f"**Current Status**: EXECUTED\n\n**Executed**: {timestamp.isoformat()}\n**Result**: Published to {mock_url}"
        )
        action_file.write_text(action_content, encoding="utf-8")
        
        # Log to dashboard
        self._log_to_dashboard(post_id, mock_url)
        
        logger.info(f"Mock LinkedIn post created: {mock_url}")
        
        return {
            "post_id": post_id,
            "mock_url": mock_url,
            "status": "published",
            "timestamp": timestamp.isoformat()
        }

    def _log_to_dashboard(self, post_id: str, mock_url: str):
        """Log mock post to Dashboard.md"""
        timestamp = datetime.now(timezone.utc).isoformat()
        log_entry = f"| {timestamp} | mock_linkedin_post | Success ({mock_url}) | <100ms | success |\n"
        
        try:
            if self.dashboard_path.exists():
                content = self.dashboard_path.read_text(encoding="utf-8")
                
                # Find MCP Actions table
                if "### MCP Actions" in content:
                    lines = content.split("\n")
                    new_lines = []
                    inserted = False
                    
                    for line in lines:
                        new_lines.append(line)
                        if line.startswith("| Timestamp |") and "MCP Actions" not in line and not inserted:
                            new_lines.append(log_entry.rstrip())
                            inserted = True
                    
                    content = "\n".join(new_lines)
                
                self.dashboard_path.write_text(content, encoding="utf-8")
        except Exception as e:
            logger.error(f"Failed to log to dashboard: {e}")

    def run_full_workflow(self, post_content: str, topic: str = "General"):
        """
        Run complete LinkedIn mock posting workflow.
        
        Args:
            post_content: Content for the LinkedIn post
            topic: Post topic
            
        Returns:
            Result dict
        """
        print(f"\n=== LinkedIn Mock Posting Workflow ===\n")
        
        # Step 1: Generate draft
        print("[1/4] Generating LinkedIn post draft...")
        draft_path = self.generate_post_draft(post_content, topic)
        print(f"      ✓ Draft created: {draft_path}")
        
        # Step 2: Create approval request
        print("\n[2/4] Creating approval request...")
        action_id = self.create_approval_request(draft_path)
        print(f"      ✓ Approval request: {action_id}")
        print(f"      ✓ File: {self.actions_dir / action_id}.md")
        
        # Step 3: Check approval status
        print("\n[3/4] Checking approval status...")
        status = self.check_approval_status(action_id)
        print(f"      Status: {status}")
        
        if status == "PENDING":
            print("\n      ⚠ Action is pending approval.")
            print(f"      → Edit: {self.actions_dir / action_id}.md")
            print("      → Set: Approved: Yes")
            print("      → Then run with --execute flag")
            return {"status": "pending", "action_id": action_id}
        
        elif status == "REJECTED":
            print("\n      ✗ Action was rejected.")
            return {"status": "rejected"}
        
        # Step 4: Execute mock post
        print("\n[4/4] Executing mock LinkedIn post...")
        result = self.execute_mock_post(draft_path, action_id)
        print(f"      ✓ Mock post published!")
        print(f"      ✓ Mock URL: {result['mock_url']}")
        print(f"      ✓ Saved to: {self.done_dir / result['post_id']}.md")
        
        print(f"\n=== Workflow Complete ===\n")
        return result


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="LinkedIn Mock Poster")
    parser.add_argument("--execute", action="store_true", help="Execute pending approved actions")
    parser.add_argument("--content", type=str, help="Post content (for new draft)")
    parser.add_argument("--topic", type=str, default="General", help="Post topic")
    parser.add_argument("--test", action="store_true", help="Run test workflow")
    args = parser.parse_args()
    
    poster = LinkedInMockPoster()
    
    if args.test:
        # Run test workflow
        test_content = """🚀 Excited to share our latest work on AI Employee automation!

Our Silver Tier orchestration layer now supports:
✅ Multi-channel input (Gmail + Filesystem)
✅ Structured planning with approval workflows
✅ MCP server for safe external actions
✅ Scheduled autonomous workflows

This is a game-changer for productivity automation.

#AI #Automation #Productivity #Tech"""
        
        result = poster.run_full_workflow(test_content, "AI Automation")
        
    elif args.execute:
        # Execute pending approved actions
        print("\n=== Executing Pending Approved Actions ===\n")
        executed = 0
        
        for action_file in poster.actions_dir.glob("Action_*.md"):
            status = poster.check_approval_status(action_file.stem)
            
            if status == "APPROVED":
                # Find associated draft
                content = action_file.read_text(encoding="utf-8")
                draft_match = re.search(r'Plan_Reference: (.+)', content)
                
                if draft_match:
                    draft_path = Path(draft_match.group(1).strip())
                    if draft_path.exists():
                        print(f"Executing: {action_file.stem}")
                        result = poster.execute_mock_post(str(draft_path), action_file.stem)
                        print(f"  ✓ Mock URL: {result['mock_url']}")
                        executed += 1
        
        if executed == 0:
            print("No approved actions to execute.")
        else:
            print(f"\n✓ Executed {executed} action(s)")
            
    elif args.content:
        # Create new draft with content
        result = poster.run_full_workflow(args.content, args.topic)
        
    else:
        # Show help
        print("LinkedIn Mock Poster - Test LinkedIn workflow without API access")
        print("\nUsage:")
        print("  --test              Run test workflow with sample content")
        print("  --execute           Execute pending approved actions")
        print("  --content \"text\"    Create new draft with content")
        print("  --topic \"topic\"     Set post topic (default: General)")
        print("\nExamples:")
        print("  python -m ai_employee.mcp_server.actions.linkedin_mock_test --test")
        print("  python -m ai_employee.mcp_server.actions.linkedin_mock_test --execute")
        print('  python -m ai_employee.mcp_server.actions.linkedin_mock_test --content "Hello LinkedIn!"')


if __name__ == "__main__":
    main()
